import { test, expect, type Page } from '@playwright/test'
import { randomUUID } from 'node:crypto'

const image = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFklEQVR4nGNkYPjPwMDAxMDAwMDAAAALHwEDmIWXfgAAAABJRU5ErkJggg==', 'base64')
async function register(page: Page, name: string) {
  await page.goto('/register')
  await page.getByLabel('校园邮箱', { exact: true }).fill(`ui-${randomUUID()}@example.invalid`)
  await page.getByLabel('昵称', { exact: true }).fill(name)
  await page.getByLabel('密码', { exact: true }).fill('Valid@12345')
  await page.getByRole('button', { name: '注册并登录', exact: true }).click()
  await expect(page).toHaveURL(/\/market$/)
}

test('real two-account browser transaction; no database editing', async ({ browser }) => {
  const buyerContext = await browser.newContext()
  const sellerContext = await browser.newContext()
  const buyer = await buyerContext.newPage(), seller = await sellerContext.newPage()
  const errors: string[] = []
  for (const page of [buyer, seller]) page.on('pageerror', (error) => errors.push(error.name))
  await register(seller, 'Seller')
  await seller.getByRole('button', { name: '发布商品', exact: true }).click()
  const title = `UI Book ${randomUUID().slice(0, 8)}`
  await seller.getByLabel('商品名称', { exact: true }).fill(title)
  const uploaded = seller.waitForResponse((response) => response.url().includes('/uploads/images') && response.request().method() === 'POST')
  await seller.locator('input[type=file]').setInputFiles({ name: 'demo.png', mimeType: 'image/png', buffer: image })
  expect((await uploaded).status()).toBe(201)
  await seller.getByLabel('出售价格（元）', { exact: true }).fill('50')
  await seller.getByLabel('校内交易地点', { exact: true }).fill('Library')
  await expect(seller.getByRole('button', { name: '保存商品' })).toBeEnabled()
  await seller.getByRole('button', { name: '保存商品' }).click()
  await expect(seller).toHaveURL(/\/product\/\d+$/)
  await expect.poll(() => seller.locator('.ant-image img').first().evaluate((element) => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  const productPath = new URL(seller.url()).pathname
  await register(buyer, 'Buyer')
  await buyer.getByRole('searchbox', { name: '搜索商品', exact: true }).fill(title)
  await buyer.getByRole('searchbox', { name: '搜索商品', exact: true }).press('Enter')
  await buyer.getByRole('link', { name: title, exact: true }).last().click()
  await buyer.getByRole('button', { name: '联系卖家', exact: true }).click()
  await expect(buyer).toHaveURL(/\/chat\/\d+$/)
  await buyer.getByRole('textbox', { name: '消息内容', exact: true }).fill('Test message')
  await buyer.getByRole('button', { name: '发送消息', exact: true }).click()
  await seller.getByRole('menuitem', { name: '聊天' }).click()
  await seller.getByRole('link', { name: new RegExp(title) }).click()
  await expect(seller.getByText('Test message', { exact: true })).toBeVisible()
  await buyer.locator('input[type=file]').setInputFiles({ name: 'chat.png', mimeType: 'image/png', buffer: image })
  await expect(buyer.getByRole('button', { name: '发送已上传图片' })).toBeEnabled()
  await buyer.getByRole('button', { name: '发送已上传图片' }).click()
  await expect(seller.locator('img[src^="blob:"]')).toBeVisible()
  await buyer.route('**/chat/sessions/*/messages', (route) => route.request().method() === 'POST' ? route.abort() : route.continue())
  await buyer.getByRole('textbox', { name: '消息内容', exact: true }).fill('Retry message')
  await buyer.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(buyer.getByText('发送失败', { exact: true })).toBeVisible()
  await buyer.unroute('**/chat/sessions/*/messages')
  await buyer.getByRole('button', { name: '重试发送', exact: true }).click()
  await expect(seller.getByText('Retry message', { exact: true })).toBeVisible()
  await buyerContext.setOffline(true)
  await expect(buyer.getByText('实时连接恢复中，可通过 HTTP 发送与补拉消息。')).toBeVisible()
  await buyerContext.setOffline(false)
  await expect(buyer.getByText('实时连接已建立')).toBeVisible()
  await expect(buyer.getByText('Retry message', { exact: true })).toHaveCount(1)
  await buyer.getByRole('spinbutton', { name: '报价金额', exact: true }).fill('45')
  await buyer.getByRole('button', { name: '提交报价', exact: true }).click()
  await seller.getByRole('button', { name: '接受报价', exact: true }).click()
  await expect(seller).toHaveURL(/\/transactions\/\d+$/)
  const orderPath = new URL(seller.url()).pathname
  await seller.getByRole('link', { name: '安排见面', exact: true }).click()
  await seller.getByLabel('校内见面地点', { exact: true }).fill('Library')
  await seller.getByLabel('日期', { exact: true }).fill('2026-10-12')
  await seller.getByLabel('开始时间', { exact: true }).fill('12:00')
  await seller.getByLabel('结束时间', { exact: true }).fill('13:00')
  await seller.getByRole('button', { name: '保存新约定', exact: true }).click()
  await seller.getByRole('button', { name: '确认当前版本', exact: true }).click()
  await buyer.getByRole('link', { name: '查看订单', exact: true }).click()
  await expect(buyer).toHaveURL(new RegExp(orderPath + '$'))
  await buyer.getByRole('button', { name: '确认当前版本', exact: true }).click()
  for (const page of [seller, buyer]) {
    await page.getByRole('button', { name: '我已完成交易', exact: true }).click()
    await page.getByRole('button', { name: 'OK', exact: true }).click()
  }
  await expect(buyer.getByText('已完成', { exact: true }).first()).toBeVisible()
  await buyer.getByRole('link', { name: '评价交易', exact: true }).click()
  for (const field of ['overall', 'descriptionAccuracy', 'communication', 'punctuality']) {
    await buyer.locator(`#${field} .ant-rate-star`).nth(4).click()
  }
  await buyer.getByRole('button', { name: '提交评价', exact: true }).click()
  await expect(buyer.getByText('评价已保存。', { exact: true })).toBeVisible()
  await buyer.getByRole('link', { name: '返回订单', exact: true }).click()
  await buyer.getByRole('button', { name: /举\s*报/ }).click()
  await buyer.getByLabel('举报原因', { exact: true }).click()
  await buyer.getByText('其他违规', { exact: true }).click()
  await buyer.getByRole('button', { name: '提交举报', exact: true }).click()
  await expect(buyer.getByRole('dialog')).not.toBeVisible()
  await buyer.getByRole('button', { name: '通知', exact: true }).click()
  await expect(buyer.getByRole('heading', { name: '通知与举报记录' })).toBeVisible()
  await buyer.getByRole('button', { name: '全部已读', exact: true }).click()
  expect(errors).toEqual([])
  expect(productPath).toMatch(/\/product\/\d+/)
  await buyerContext.close(); await sellerContext.close()
})

test('wanted constraints and price baseline are real services', async ({ page }) => {
  await register(page, 'Wanted tester')
  await page.getByRole('menuitem', { name: '求购' }).click()
  await page.getByRole('button', { name: '发布求购', exact: true }).click()
  await page.getByLabel('想买什么', { exact: true }).fill('book')
  await page.getByLabel('最低预算', { exact: true }).fill('0')
  await page.getByLabel('最高预算', { exact: true }).fill('100')
  await page.getByRole('button', { name: '保存求购', exact: true }).click()
  await expect(page).toHaveURL(/\/wanted\/\d+$/)
  await page.getByRole('link', { name: '规则匹配结果', exact: true }).click()
  await expect(page.getByRole('heading', { name: '规则匹配结果' })).toBeVisible()
  await page.getByRole('menuitem', { name: '首页' }).click()
  await page.getByRole('button', { name: '发布商品', exact: true }).click()
  await page.getByRole('link', { name: '查看规则价格建议', exact: true }).click()
  await page.getByLabel('原价（元）', { exact: true }).fill('100')
  await page.getByRole('button', { name: '计算区间', exact: true }).click()
  await expect(page.getByText(/规则参考区间：¥/)).toBeVisible()
})

test('guest browse, failure recovery, secure reload restoration, logout and fixed navigation', async ({ page }) => {
  await page.goto('/market')
  await expect(page.getByRole('heading', { name: '校园市场' })).toBeVisible()
  await expect(page.getByRole('link', { name: '登录', exact: true })).toBeVisible()
  const side = await page.locator('.app-sidebar').boundingBox()
  await page.getByRole('menuitem', { name: '求购' }).click()
  expect(await page.locator('.app-sidebar').boundingBox()).toEqual(side)
  await page.route('**/products**', (route) => route.abort())
  await page.getByRole('menuitem', { name: '首页' }).click()
  await expect(page.getByRole('button', { name: /重\s*试/ })).toBeVisible()
  await page.unroute('**/products**')
  await page.getByRole('button', { name: /重\s*试/ }).click()
  await expect(page.getByRole('button', { name: /重\s*试/ })).not.toBeVisible()
  await register(page, 'Reload test')
  await page.reload()
  await expect(page.getByText('Reload test', { exact: true })).toBeVisible()
  await page.goto('/profile')
  await expect(page.getByRole('heading', { name: '个人资料' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '个人资料' })).toBeVisible()
  let expired = false
  await page.route('**/users/me', (route) => {
    if (!expired) { expired = true; return route.fulfill({ status: 401, json: { code: 'AUTH_UNAUTHORIZED', message: 'Expired fixture', requestId: 'safe-test' } }) }
    return route.continue()
  })
  await page.getByRole('menuitem', { name: '首页' }).click()
  const renewed = page.waitForResponse((response) => response.url().endsWith('/auth/browser-session') && response.status() === 200)
  await page.getByText('Reload test', { exact: true }).hover()
  await page.getByRole('menuitem', { name: '个人中心' }).click()
  await renewed
  await expect(page.getByRole('heading', { name: '个人资料' })).toBeVisible()
  await expect(page.getByRole('button', { name: '保存资料' })).toBeVisible()
  await page.unroute('**/users/me')
  expect(await page.evaluate(() => Object.keys(localStorage).filter((key) => /token|auth|session/i.test(key)))).toEqual([])
  expect(await page.evaluate(() => document.cookie)).not.toMatch(/campusloop.*session/)
  const cookies = await page.context().cookies()
  const session = cookies.find((cookie) => /campusloop.*session/.test(cookie.name))
  expect(session?.httpOnly).toBe(true)
  expect(session?.sameSite).toBe('Strict')
  await page.getByText('Reload test', { exact: true }).hover()
  await page.getByRole('menuitem', { name: '退出登录' }).click()
  await expect(page.getByRole('link', { name: '登录', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('link', { name: '登录', exact: true })).toBeVisible()
})

test('mobile navigation and empty-state filter recovery', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/market')
  await expect(page.getByRole('navigation', { name: '移动导航' })).toBeVisible()
  await expect(page.locator('.app-sidebar')).not.toBeVisible()
  await page.getByRole('searchbox', { name: '搜索商品', exact: true }).fill(`nonexistent-${randomUUID()}`)
  await page.getByRole('searchbox', { name: '搜索商品', exact: true }).press('Enter')
  await expect(page.getByText('没有符合筛选条件的结果，请调整条件。', { exact: true })).toBeVisible()
  const nav = await page.getByRole('navigation', { name: '移动导航' }).boundingBox()
  await page.getByRole('navigation', { name: '移动导航' }).getByRole('button', { name: '求购' }).click()
  expect(await page.getByRole('navigation', { name: '移动导航' }).boundingBox()).toEqual(nav)
})

test('another tab changing account cannot retry an old request as the new user', async ({ context, page }) => {
  await register(page, 'Original account')
  const other = await context.newPage()
  await register(other, 'Changed account')
  let attempts = 0
  await page.route('**/users/me', (route) => {
    attempts += 1
    return route.fulfill({ status: 401, json: { code: 'AUTH_UNAUTHORIZED', message: 'Expired fixture', requestId: 'safe-test' } })
  })
  await page.getByText('Original account', { exact: true }).hover()
  const renewed = page.waitForResponse((response) => response.url().endsWith('/auth/browser-session') && response.status() === 200)
  await page.getByRole('menuitem', { name: '个人中心' }).click()
  await renewed
  await expect(page.getByRole('link', { name: '登录', exact: true })).toBeVisible()
  expect(attempts).toBe(1)
  await page.unroute('**/users/me')
  await page.reload()
  await expect(page.getByText('Changed account', { exact: true })).toBeVisible()
  await other.close()
})
